"""add notification_settings table
Revision ID: 0f09af0f2b2b
Revises: c2b3d4e5f6a7
Create Date: 2026-06-17 11:38:26.784528
"""

from alembic import op
import sqlalchemy as sa

revision = '0f09af0f2b2b'
down_revision = 'c2b3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_email', sa.String(length=320), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_address', sa.String(length=320), nullable=True),
    sa.Column('webhook_enabled', sa.Boolean(), nullable=False),
    sa.Column('webhook_url', sa.String(length=1024), nullable=True),
    sa.Column('min_severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_settings_owner_email'), 'notification_settings', ['owner_email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_settings_owner_email'), table_name='notification_settings')
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
